version: 2
updates:
- package-ecosystem: maven
  directory: "/sevntu-checks"
  schedule:
    interval: weekly
    day: "friday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: dependency
- package-ecosystem: maven
  directory: "/sevntu-checkstyle-idea-extension"
  schedule:
    interval: weekly
    day: "friday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: dependency
- package-ecosystem: maven
  directory: "/sevntu-checkstyle-sonar-plugin"
  schedule:
    interval: weekly
    day: "friday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: dependency
