#############################################################################
# GitHub Action to bump license year
#
# Workflow starts every new year.
#
#############################################################################
name: "Bump license year"
on:
  schedule:
    - cron: "0 2 1 1 *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  bump:
    name: Bump license year
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v3
      - name: Set Current Year
        run: |
          echo "YEAR=$(date +'%Y')" >> "$GITHUB_ENV"
      - name: Modify Files
        run: |
          ./.ci/bump-license-year.sh $(("${{ env.YEAR }}" - 1)) ${{ env.YEAR }} .
      - name: Push commit
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "minor: Bump year to ${{ env.YEAR }}"
          git push
