name: "checks"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  no-exception:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - struts
          - guava
          - hibernate-orm
          - spotbugs
          - spring-framework
          - hbase
          - pmd-elasticsearch-lombok-ast
          - alot-of-projects

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install groovy
        run: sudo apt install groovy
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checks Setup
        run: ./.ci/checks-no-exception.sh setup
      - name: Execute
        run: ./.ci/checks-no-exception.sh ${{ matrix.profile }}
