name: "validation"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        profile:
          - eclipse-cs
          - idea-extension
          - sonar-plugin
          - sevntu-checks
          - all-sevntu-checks-contribution
          - checkstyle-regression
          - eclipse-analysis
          - sonarqube

    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute
        run: ./.ci/validation.sh ${{ matrix.profile }}
      - name: Git-Diff
        run: ./.ci/validation.sh git-diff
